#!/usr/bin/env groovy
pipeline {
  agent any
  tools {nodejs "nodejs"}
  stages {
    stage('Cloning Repository') {
      steps {
        git branch: 'jenkins-pipeline-setup', credentialsId: 'valorant-jenkins-repo-auth-token', url: 'https://github.com/ShabazBadshah/valorant'
        sh "ls -la"
      }
    } 
    stage('Installing Dependencies') {
      steps {
        sh 'npm --version'
        dir('app') {
            echo 'Installing app dependencies' 
            sh 'npm install'
            sh "pwd"
        }
      }
    }
    stage('Testing') {
      options {
         timeout(time: 5, unit: 'MINUTES')   // timeout on this stage
      }
      steps {
        dir('app') {
          sh 'pwd'
          sh "APP_PORT=8080 node index.js &"
          sh 'npm run test:ci'
          sh 'npm prune'
          sh 'rm node_modules -rf'
        }
      }
    }
  }
}